const { injectPostInstall, withPodfilePostInstall } = require('./podfilePostInstall');

/**
 * Raises every CocoaPods target's IPHONEOS_DEPLOYMENT_TARGET to a floor.
 *
 * Why: many third-party pods still declare very old minimums (9.0, 12.0, 12.4,
 * 13.0, 13.4, ...). Recent Xcode releases only support deployment targets from
 * 15.0 upwards and refuse to build the Pods project otherwise:
 *
 *   The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.4,
 *   but the range of supported deployment target versions is 15.0 to 27.0.x.
 *
 * The app itself targets react-native's minimum (15.1 on RN 0.83), so lifting
 * pods to that same floor cannot make the app incompatible with any of them.
 *
 * ios/ is regenerated by `expo prebuild`, so editing the Podfile by hand does
 * not stick; this plugin re-applies the patch on every prebuild.
 */

const DEFAULT_MIN_IOS = '15.1';
const MARKER = '# happy: raise legacy pod deployment targets';

function buildSnippet(minIos) {
  return `
    ${MARKER}
    happy_min_ios = Gem::Version.new('${minIos}')
    raise_target = lambda do |build_config|
      current = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      next if current.nil? || current.to_s.empty?
      if Gem::Version.new(current.to_s) < happy_min_ios
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${minIos}'
      end
    end
    installer.pods_project.build_configurations.each(&raise_target)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each(&raise_target)
    end
`;
}

function patchPodfile(contents, minIos) {
  return injectPostInstall(contents, {
    marker: MARKER,
    snippet: buildSnippet(minIos),
    pluginName: 'withPodsDeploymentTarget',
  });
}

module.exports = function withPodsDeploymentTarget(config, { minIos = DEFAULT_MIN_IOS } = {}) {
  return withPodfilePostInstall(config, {
    marker: MARKER,
    snippet: buildSnippet(minIos),
    pluginName: 'withPodsDeploymentTarget',
  });
};

module.exports.patchPodfile = patchPodfile;
