const { withXcodeProject } = require('@expo/config-plugins');

/**
 * Turns Xcode's User Script Sandboxing off for the app target.
 *
 * React Native's "Bundle React Native code and images" phase writes into the app
 * bundle (`ip.txt` for Debug device builds, `main.jsbundle` for Release). With
 * sandboxing on, that write is refused and the build dies with:
 *
 *   .../Debug-iphoneos/Happydev.app/ip.txt: Operation not permitted
 *   Command PhaseScriptExecution failed with a nonzero exit code
 *
 * The phase declares no outputs, so it cannot run sandboxed. React Native's own
 * template sets this to NO for the same reason. Expo's generated project leaves it
 * unset, so Xcode's default applies, and Xcode 27 evidently defaults it on.
 *
 * ios/ is regenerated by `expo prebuild`, so the setting is re-applied each time.
 */
module.exports = function withIosUserScriptSandboxingOff(config) {
  return withXcodeProject(config, (cfg) => {
    const configurations = cfg.modResults.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      if (entry && entry.buildSettings && entry.buildSettings.PRODUCT_NAME) {
        entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
      }
    }
    return cfg;
  });
};
