const { withPodfileProperties, withXcodeProject } = require('@expo/config-plugins');
const { injectPostInstall, withPodfilePostInstall } = require('./podfilePostInstall');

/**
 * Sets one iOS deployment-target floor for the app, the Podfile and every pod.
 *
 * Two separate build failures come from native code written for an older iOS
 * floor than the one the toolchain now accepts or assumes.
 *
 * 1) Pods declaring targets Xcode no longer supports. Recent Xcode releases only
 *    accept deployment targets from 15.0 upwards, and many pods still declare
 *    9.0, 12.0, 12.4, 13.0, 13.4 ...:
 *
 *      The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.4,
 *      but the range of supported deployment target versions is 15.0 to 27.0.x.
 *
 * 2) APIs the new SDK now marks as newer than the pod's declared minimum. expo-router
 *    declares iOS 15.1 but calls UIAction.subtitle without an availability check;
 *    the iOS 27 SDK reports it as iOS 16.0+:
 *
 *      expo-router/ios/LinkPreview/LinkPreviewNativeActionView.swift:141:20
 *      'subtitle' is only available in iOS 16.0 or newer
 *
 *    Upstream expo/expo main still has that unguarded code, and no 55.x release
 *    fixes it, so a version bump cannot help. Raising the floor makes the API
 *    available without touching third-party sources.
 *
 * The floor must be applied to the app too, not only to the pods: linking
 * static libraries built for a newer iOS than the app targets draws linker
 * warnings. So this plugin sets all three places that carry the number:
 *   - Podfile.properties.json `ios.deploymentTarget` (read by the Podfile's
 *     `platform :ios` line),
 *   - every IPHONEOS_DEPLOYMENT_TARGET in the app's Xcode project,
 *   - every pod target, via an injected post_install step.
 *
 * 16.0 is the lowest floor that fixes the proven error. It costs nothing on a
 * current device (iPhone 16 Pro Max ships with iOS 18), and drops only iOS 15,
 * which this build does not target. If another "only available in iOS 17.0"
 * error ever appears, raise DEFAULT_MIN_IOS here and nowhere else.
 *
 * ios/ is regenerated by `expo prebuild`, so a hand-edit would not stick; this
 * plugin re-applies the floor every time.
 */

const DEFAULT_MIN_IOS = '16.0';
const MARKER = '# happy: raise legacy pod deployment targets';

/** Compares dotted versions numerically: "15.1" < "16.0", "9.0" < "15.1". */
function isLower(a, b) {
  const pa = String(a).split('.').map(Number);
  const pb = String(b).split('.').map(Number);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const x = pa[i] || 0;
    const y = pb[i] || 0;
    if (x !== y) return x < y;
  }
  return false;
}

function buildSnippet(minIos) {
  return `
    ${MARKER}
    happy_min_ios = Gem::Version.new('${minIos}')
    raise_target = lambda do |build_config|
      current = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      next if current.nil? || current.to_s.empty?
      if Gem::Version.new(current.to_s) < happy_min_ios
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${minIos}'
      end
    end
    installer.pods_project.build_configurations.each(&raise_target)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each(&raise_target)
    end
`;
}

function patchPodfile(contents, minIos) {
  return injectPostInstall(contents, {
    marker: MARKER,
    snippet: buildSnippet(minIos),
    pluginName: 'withIosDeploymentTarget',
  });
}

function raiseXcodeProjectTargets(project, minIos) {
  const configs = project.pbxXCBuildConfigurationSection();
  for (const key of Object.keys(configs)) {
    const settings = configs[key] && configs[key].buildSettings;
    if (!settings || settings.IPHONEOS_DEPLOYMENT_TARGET == null) continue;
    const current = String(settings.IPHONEOS_DEPLOYMENT_TARGET).replace(/"/g, '');
    if (isLower(current, minIos)) {
      settings.IPHONEOS_DEPLOYMENT_TARGET = minIos;
    }
  }
}

module.exports = function withIosDeploymentTarget(config, { minIos = DEFAULT_MIN_IOS } = {}) {
  // 1. Podfile.properties.json -> the Podfile's `platform :ios, ...` line.
  config = withPodfileProperties(config, (cfg) => {
    const current = cfg.modResults['ios.deploymentTarget'];
    if (!current || isLower(current, minIos)) {
      cfg.modResults['ios.deploymentTarget'] = minIos;
    }
    return cfg;
  });

  // 2. The app target's own build settings.
  config = withXcodeProject(config, (cfg) => {
    raiseXcodeProjectTargets(cfg.modResults, minIos);
    return cfg;
  });

  // 3. Every pod target.
  return withPodfilePostInstall(config, {
    marker: MARKER,
    snippet: buildSnippet(minIos),
    pluginName: 'withIosDeploymentTarget',
  });
};

module.exports.patchPodfile = patchPodfile;
module.exports.isLower = isLower;
module.exports.DEFAULT_MIN_IOS = DEFAULT_MIN_IOS;
